"""Analyst dashboard for SentinelAI: review alerts and record decisions."""

from pathlib import Path

import streamlit as st

from sentinelai.audit import latest_decisions, record_decision
from sentinelai.detections import (
    detect_repeated_authentication_failures,
    detect_success_after_failures,
    detect_suspicious_web_path_scan,
)
from sentinelai.ingestion import load_jsonl_events
from sentinelai.models import AlertStatus
from sentinelai.triage import OllamaUnavailableError, generate_triage

if "ai_triage_cache" not in st.session_state:
    st.session_state.ai_triage_cache = {}

st.set_page_config(page_title="SentinelAI", page_icon="🛡️", layout="wide")
st.title("🛡️ SentinelAI")
st.caption("Human-in-the-loop security event triage — synthetic data only")

sample_log = Path("data/samples/auth_events.jsonl")
events = load_jsonl_events(sample_log)
alerts = [
    *detect_repeated_authentication_failures(events),
    *detect_success_after_failures(events),
    *detect_suspicious_web_path_scan(events),
]

decisions = latest_decisions()

pending = [a for a in alerts if a.alert_id not in decisions]
reviewed = [a for a in alerts if a.alert_id in decisions]

col1, col2, col3 = st.columns(3)
col1.metric("Normalised events", len(events))
col2.metric("Alerts awaiting review", len(pending))
col3.metric("Alerts reviewed", len(reviewed))

st.divider()

for alert in alerts:
    decision = decisions.get(alert.alert_id)
    status_label = decision.decision if decision else AlertStatus.PENDING_REVIEW
    header = f"{alert.severity.upper()} · {alert.title} — {status_label.replace('_', ' ').title()}"

    with st.expander(header, expanded=decision is None):
        st.progress(alert.risk_score, text=f"Risk score: {alert.risk_score}/100")
        st.write(alert.summary)

        st.subheader("Evidence")
        st.json([event.model_dump(mode="json") for event in alert.evidence])

        st.subheader("Recommended next step")
        st.write(alert.recommendation)
        st.info("No action is performed automatically. An analyst must review this alert.")

        st.subheader("AI explanation (draft — verify before relying on it)")
        cached = st.session_state.ai_triage_cache.get(alert.alert_id)
        if cached is not None:
            st.markdown(cached.explanation)
            st.caption(f"Generated by {cached.model_used} · not a substitute for the rule-based risk score above")
        elif st.button("🤖 Explain with local AI (Ollama)", key=f"ai-{alert.alert_id}"):
            with st.spinner("Asking local model..."):
                try:
                    triage = generate_triage(alert)
                    st.session_state.ai_triage_cache[alert.alert_id] = triage
                    st.rerun()
                except OllamaUnavailableError as exc:
                    st.error(str(exc))

        st.subheader("Analyst decision")
        if decision is not None:
            st.success(
                f"Marked as **{decision.decision.replace('_', ' ')}** on "
                f"{decision.decided_at:%Y-%m-%d %H:%M UTC}"
                + (f" — note: {decision.analyst_note}" if decision.analyst_note else "")
            )
        else:
            note = st.text_input("Note (optional)", key=f"note-{alert.alert_id}")
            btn_col1, btn_col2 = st.columns(2)
            if btn_col1.button("✅ Confirm alert", key=f"confirm-{alert.alert_id}"):
                record_decision(alert.alert_id, AlertStatus.CONFIRMED, note or None)
                st.rerun()
            if btn_col2.button("🚫 Mark false positive", key=f"fp-{alert.alert_id}"):
                record_decision(alert.alert_id, AlertStatus.FALSE_POSITIVE, note or None)
                st.rerun()
