"""Analyst dashboard for SentinelAI: review alerts and record decisions."""

from pathlib import Path

import streamlit as st

from sentinelai.audit import (
    first_seen_times,
    history_for_source_ips,
    latest_decisions,
    record_decision,
    record_first_seen,
)
from sentinelai.detections import (
    detect_repeated_authentication_failures,
    detect_success_after_failures,
    detect_suspicious_web_path_scan,
)
from sentinelai.ingestion import load_jsonl_events_from_dir
from sentinelai.metrics import compute_review_metrics, format_duration
from sentinelai.models import AlertStatus
from sentinelai.triage import OllamaUnavailableError, generate_triage

if "ai_triage_cache" not in st.session_state:
    st.session_state.ai_triage_cache = {}

st.set_page_config(page_title="SentinelAI", page_icon="🛡️", layout="wide")
st.title("🛡️ SentinelAI")
st.caption("Human-in-the-loop security event triage — synthetic data only")

# Load every synthetic sample log (auth + web) from the samples directory.
ingestion = load_jsonl_events_from_dir(Path("data/samples"))
events = ingestion.events

if ingestion.has_skipped_lines:
    with st.expander(f"⚠️ {len(ingestion.skipped)} log line(s) could not be parsed", expanded=False):
        for skipped in ingestion.skipped:
            st.write(f"`{skipped.source}` line {skipped.line_number}: {skipped.reason}")

if not events:
    st.warning("No events loaded from data/samples/ — add a .jsonl log file to see alerts.")
    st.stop()
alerts = [
    *detect_repeated_authentication_failures(events),
    *detect_success_after_failures(events),
    *detect_suspicious_web_path_scan(events),
]

record_first_seen(alert.alert_id for alert in alerts)
decisions = latest_decisions()
metrics = compute_review_metrics(alerts, decisions, first_seen_times())

pending = [a for a in alerts if a.alert_id not in decisions]
reviewed = [a for a in alerts if a.alert_id in decisions]

col1, col2, col3 = st.columns(3)
col1.metric("Normalised events", len(events))
col2.metric("Alerts awaiting review", len(pending))
col3.metric("Alerts reviewed", len(reviewed))

st.subheader("Review metrics")
m1, m2, m3 = st.columns(3)
m1.metric(
    "False positive rate",
    "n/a" if metrics.false_positive_rate is None else f"{metrics.false_positive_rate:.0%}",
    help="Alerts marked as false positive / alerts reviewed so far.",
)
m2.metric(
    "Median time to review",
    format_duration(metrics.median_seconds_to_review),
    help="From the moment an alert was first shown to the analyst's decision.",
)
m3.metric("Confirmed / false positive", f"{metrics.confirmed} / {metrics.false_positives}")
st.table(
    [
        {
            "Severity": severity.value.title(),
            "Alerts": counts.total,
            "Pending": counts.pending,
            "Confirmed": counts.confirmed,
            "False positive": counts.false_positive,
        }
        for severity, counts in metrics.by_severity.items()
        if counts.total
    ]
)

st.divider()

for alert in alerts:
    decision = decisions.get(alert.alert_id)
    status_label = decision.decision if decision else AlertStatus.PENDING_REVIEW
    header = f"{alert.severity.upper()} · {alert.title} — {status_label.replace('_', ' ').title()}"

    with st.expander(header, expanded=decision is None):
        st.progress(alert.risk_score, text=f"Risk score: {alert.risk_score}/100")
        st.write(alert.summary)

        if alert.mitre_techniques:
            st.markdown(
                "**MITRE ATT&CK:** "
                + " · ".join(
                    f"[{t.technique_id} {t.name}]({t.url}) ({', '.join(t.tactics)})"
                    for t in alert.mitre_techniques
                )
            )

        st.subheader("Evidence")
        st.json([event.model_dump(mode="json") for event in alert.evidence])

        st.subheader("Recommended next step")
        st.write(alert.recommendation)
        st.info("No action is performed automatically. An analyst must review this alert.")

        st.subheader("AI explanation (draft — verify before relying on it)")
        source_ips = sorted({e.source_ip for e in alert.evidence})
        history = history_for_source_ips(source_ips, exclude_alert_id=alert.alert_id)
        if history.has_history:
            st.caption(
                f"🔎 Agent lookup: {', '.join(source_ips)} seen in "
                f"{history.times_seen} previously reviewed alert(s) — "
                f"{history.confirmed} confirmed, {history.false_positive} false positive."
            )
        else:
            st.caption(f"🔎 Agent lookup: no prior review history for {', '.join(source_ips)}.")

        cached = st.session_state.ai_triage_cache.get(alert.alert_id)
        if cached is not None:
            st.markdown(cached.explanation)
            st.caption(
                f"Generated by {cached.model_used} · "
                "not a substitute for the rule-based risk score above"
            )
        elif st.button("🤖 Explain with local AI (Ollama)", key=f"ai-{alert.alert_id}"):
            with st.spinner("Asking local model..."):
                try:
                    triage = generate_triage(alert)
                    st.session_state.ai_triage_cache[alert.alert_id] = triage
                    st.rerun()
                except OllamaUnavailableError as exc:
                    st.error(str(exc))

        st.subheader("Analyst decision")
        if decision is not None:
            st.success(
                f"Marked as **{decision.decision.replace('_', ' ')}** on "
                f"{decision.decided_at:%Y-%m-%d %H:%M UTC}"
                + (f" — note: {decision.analyst_note}" if decision.analyst_note else "")
            )
        else:
            note = st.text_input("Note (optional)", key=f"note-{alert.alert_id}")
            btn_col1, btn_col2 = st.columns(2)
            if btn_col1.button("✅ Confirm alert", key=f"confirm-{alert.alert_id}"):
                record_decision(
                    alert.alert_id,
                    AlertStatus.CONFIRMED,
                    note or None,
                    source_ips=sorted({e.source_ip for e in alert.evidence}),
                    rule_title=alert.title,
                )
                st.rerun()
            if btn_col2.button("🚫 Mark false positive", key=f"fp-{alert.alert_id}"):
                record_decision(
                    alert.alert_id,
                    AlertStatus.FALSE_POSITIVE,
                    note or None,
                    source_ips=sorted({e.source_ip for e in alert.evidence}),
                    rule_title=alert.title,
                )
                st.rerun()
