"""AI-assisted alert triage, backed by a local Ollama model.

Design principle: the model never decides severity, risk score or evidence —
those already come from the deterministic detection rules in detections.py.
The model's only job is to read the already-computed facts and produce a
human-readable explanation and an expanded mitigation suggestion. Its output
is a *draft for an analyst to verify*, never an automatic action.

Requires Ollama running locally (https://ollama.com) with a model pulled,
e.g.:
    ollama pull llama3.2
    ollama serve   (usually starts automatically after install)
"""

import requests

from sentinelai.models import Alert, AITriage

DEFAULT_OLLAMA_HOST = "http://localhost:11434"
DEFAULT_MODEL = "llama3.2"

SYSTEM_INSTRUCTIONS = """You are a security triage assistant helping a human analyst.
You are given an alert that was already generated by deterministic detection \
rules: its severity, risk score and evidence are FIXED FACTS, already decided. \
Do not invent, question, or restate different numbers for them.

Your only job:
1. Explain in plain, non-technical-manager-friendly language why this pattern \
of events is suspicious, referencing only the evidence given below — never \
invent log lines, IPs, usernames or timestamps that are not listed.
2. Expand the recommendation into 2-4 concrete, actionable steps an analyst \
could take, building on (not replacing) the recommendation already given.

Keep your answer under 150 words. Do not repeat the raw evidence back \
verbatim — refer to it, don't dump it. This is a draft for a human analyst \
to review, not a final decision."""


def build_prompt(alert: Alert) -> str:
    """Turn an already-computed Alert into a prompt grounded in its own evidence."""
    evidence_lines = "\n".join(
        f"- {event.timestamp.isoformat()} | {event.event_type} | "
        f"source_ip={event.source_ip} | username={event.username or 'n/a'} | "
        f"target={event.target or 'n/a'} | {event.message}"
        for event in alert.evidence
    )

    return (
        f"{SYSTEM_INSTRUCTIONS}\n\n"
        f"--- Alert (already computed by rules, do not change) ---\n"
        f"Title: {alert.title}\n"
        f"Severity: {alert.severity}\n"
        f"Risk score: {alert.risk_score}/100\n"
        f"Rule summary: {alert.summary}\n"
        f"Existing recommendation: {alert.recommendation}\n\n"
        f"--- Evidence (the only events you may reference) ---\n"
        f"{evidence_lines}\n\n"
        f"--- Your task ---\n"
        f"Write the explanation and expanded recommendation now."
    )


class OllamaUnavailableError(RuntimeError):
    """Raised when the local Ollama server cannot be reached."""


def generate_triage(
    alert: Alert,
    model: str = DEFAULT_MODEL,
    host: str = DEFAULT_OLLAMA_HOST,
    timeout_seconds: float = 60.0,
) -> AITriage:
    """Call the local Ollama model and return its explanation as an AITriage.

    Raises OllamaUnavailableError if the local server cannot be reached, so
    the caller (the dashboard) can show a clear message instead of a crash.
    """
    prompt = build_prompt(alert)

    try:
        response = requests.post(
            f"{host}/api/generate",
            json={"model": model, "prompt": prompt, "stream": False},
            timeout=timeout_seconds,
        )
        response.raise_for_status()
    except requests.RequestException as exc:
        raise OllamaUnavailableError(
            f"Could not reach Ollama at {host}. Is it running? "
            f"(try 'ollama serve' and 'ollama pull {model}')"
        ) from exc

    explanation = response.json().get("response", "").strip()
    if not explanation:
        raise OllamaUnavailableError(
            f"Ollama returned an empty response for model '{model}'. "
            f"Check that the model is pulled: 'ollama pull {model}'."
        )

    return AITriage(alert_id=alert.alert_id, model_used=model, explanation=explanation)
