"""AI-assisted alert triage, backed by a local Ollama model.

Design principle: the model never decides severity, risk score or evidence —
those already come from the deterministic detection rules in detections.py.
The model's only job is to read the already-computed facts and produce a
human-readable explanation and an expanded mitigation suggestion. Its output
is a *draft for an analyst to verify*, never an automatic action.

Requires Ollama running locally (https://ollama.com) with a model pulled,
e.g.:
    ollama pull llama3.2
    ollama serve   (usually starts automatically after install)

Agentic step: before calling the model, generate_triage() first looks up
each source IP's history in the audit log (a plain Python "tool call", no
AI involved) via sentinelai.audit.history_for_source_ips. That retrieved
context is then handed to the model as another fixed fact it must not
contradict - so the model reasons over more than just the single alert in
front of it, without ever inventing the history itself.
"""

import requests

from sentinelai.audit import DEFAULT_AUDIT_LOG, SourceIPHistory, history_for_source_ips
from sentinelai.models import AITriage, Alert

DEFAULT_OLLAMA_HOST = "http://localhost:11434"
DEFAULT_MODEL = "llama3.2"

SYSTEM_INSTRUCTIONS = """You are a security triage assistant helping a human analyst.
You are given an alert that was already generated by deterministic detection \
rules: its severity, risk score and evidence are FIXED FACTS, already decided. \
Do not invent, question, or restate different numbers for them.

Your only job:
1. Explain in plain, non-technical-manager-friendly language why this pattern \
of events is suspicious, referencing only the evidence given below — never \
invent log lines, IPs, usernames or timestamps that are not listed.
2. If prior history for these source IPs is given below, factor it into your \
explanation (e.g. a repeat offender is more concerning than a first sighting) \
— but never invent a history that isn't given.
3. Expand the recommendation into 2-4 concrete, actionable steps an analyst \
could take, building on (not replacing) the recommendation already given.

Keep your answer under 150 words. Do not repeat the raw evidence back \
verbatim — refer to it, don't dump it. This is a draft for a human analyst \
to review, not a final decision."""


def _describe_history(history: SourceIPHistory) -> str:
    if not history.has_history:
        return "No prior reviewed alerts for these source IPs — this is the first sighting."
    return (
        f"These source IPs appeared in {history.times_seen} previously reviewed alert(s): "
        f"{history.confirmed} confirmed as real incidents, "
        f"{history.false_positive} marked as false positives."
    )


def build_prompt(alert: Alert, history: SourceIPHistory) -> str:
    """Turn an already-computed Alert plus its retrieved history into a prompt."""
    evidence_lines = "\n".join(
        f"- {event.timestamp.isoformat()} | {event.event_type} | "
        f"source_ip={event.source_ip} | username={event.username or 'n/a'} | "
        f"target={event.target or 'n/a'} | {event.message}"
        for event in alert.evidence
    )

    techniques = ", ".join(
        f"{t.technique_id} {t.name}" for t in alert.mitre_techniques
    ) or "none mapped"

    return (
        f"{SYSTEM_INSTRUCTIONS}\n\n"
        f"--- Alert (already computed by rules, do not change) ---\n"
        f"Title: {alert.title}\n"
        f"Severity: {alert.severity}\n"
        f"Risk score: {alert.risk_score}/100\n"
        f"MITRE ATT&CK (assigned by the rule, do not add or change): {techniques}\n"
        f"Rule summary: {alert.summary}\n"
        f"Existing recommendation: {alert.recommendation}\n\n"
        f"--- Evidence (the only events you may reference) ---\n"
        f"{evidence_lines}\n\n"
        f"--- Analyst history for these source IP(s), from the audit log "
        f"(already computed, do not invent different numbers) ---\n"
        f"{_describe_history(history)}\n\n"
        f"--- Your task ---\n"
        f"Write the explanation and expanded recommendation now."
    )


class OllamaUnavailableError(RuntimeError):
    """Raised when the local Ollama server cannot be reached."""


def generate_triage(
    alert: Alert,
    model: str = DEFAULT_MODEL,
    host: str = DEFAULT_OLLAMA_HOST,
    timeout_seconds: float = 60.0,
    audit_log_path=DEFAULT_AUDIT_LOG,
) -> AITriage:
    """Look up source-IP history, then call the local Ollama model for an explanation.

    Raises OllamaUnavailableError if the local server cannot be reached, so
    the caller (the dashboard) can show a clear message instead of a crash.
    """
    source_ips = sorted({event.source_ip for event in alert.evidence})
    history = history_for_source_ips(
        source_ips, exclude_alert_id=alert.alert_id, log_path=audit_log_path
    )
    prompt = build_prompt(alert, history)

    try:
        response = requests.post(
            f"{host}/api/generate",
            json={"model": model, "prompt": prompt, "stream": False},
            timeout=timeout_seconds,
        )
        response.raise_for_status()
    except requests.RequestException as exc:
        raise OllamaUnavailableError(
            f"Could not reach Ollama at {host}. Is it running? "
            f"(try 'ollama serve' and 'ollama pull {model}')"
        ) from exc

    explanation = response.json().get("response", "").strip()
    if not explanation:
        raise OllamaUnavailableError(
            f"Ollama returned an empty response for model '{model}'. "
            f"Check that the model is pulled: 'ollama pull {model}'."
        )

    return AITriage(alert_id=alert.alert_id, model_used=model, explanation=explanation)
